### ISSUE TITLE
提交中文的文章会报错啊

### ISSUE THREAD

**Issue by yisake** [xuelangZF/NaHan#14]
![image](https://cloud.githubusercontent.com/assets/4221944/21072438/b54a8ab2-befd-11e6-83cc-1df713bc0832.png)

**Comment by selfboot** [comment]
数据库编码设置为 utf-8 即可。

mysql 中数据表的编码十分重要，这里我们统一用 UTF-8 编码，这样数据库，python内部操作，输出HTML全部都是 UTF-8，就不存在乱码的问题。

参考 [项目部署](https://github.com/xuelangZF/ehpc/wiki/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2)

**Comment by yisake** [comment]
@xuelangZF 貌似现在不支持发表博文的时候附带图片？？试了试拖拽是不行的

**Comment by selfboot** [comment]
拖拽是不行的，发表时编辑框支持 markdown ，所以可以用 `![]()` 来附带图片

**Comment by yisake** [comment]
![image](https://cloud.githubusercontent.com/assets/4221944/21095591/20861324-c097-11e6-88bf-32dc68f6fc8f.png)

貌似没看出来markdown的编辑框。

**Comment by selfboot** [comment]
对的，编辑框是没有显示 markdown 的一些按钮。不过确实支持，你可以写一点 markdown 语法的内容，按下 预览 来看效果。

如果前端编辑框想要 markdown 富文本编辑效果，可以用 simplemde 开源库。对它稍加改动，还可以支持 拖拽上传文件的。

**Comment by yisake** [comment]
哈哈哈，懂了，最近在做什么新项目？以后做python开发吗？

**Comment by selfboot** [comment]
在写毕业论文，以后做后台开发和算法吧。
