### ISSUE TITLE
About DB

### ISSUE THREAD

**Issue by haooodev** [xuelangZF/NaHan#15]
![screenshot_2016-12-12_16-08-43](https://cloud.githubusercontent.com/assets/18000467/21092116/817aea40-c085-11e6-969b-7ae25c6651fc.png)

**Comment by selfboot** [comment]
你的数据库运行了吗？

**Comment by Github-Benjamin** [comment]
你好，我有同样的问题，看提示信息貌似没有创建相对应的表


已解决：
>python manage.py shell
>>from nahan import db
>>db.create_all()
